let plants = [ 
  {
    photo: "https://www.costafarms.com/CostaFarms/Croton-Header-Costa-Farms-Indoor-Plant.jpg",
    nickname: "Croton",
    species: "Codiaeum spp",
    h2oFrequency: 'daily',
    careInstructions: '',
    id: 1,
  },
  {
    photo: "https://www.costafarms.com/CostaFarms/Kniphofia-Costa-Farms-Perennial-Hero.jpg",
    nickname: "Red Hot Poker",
    species: "Kniphofia spp",
    h2oFrequency: 'weekly',
    careInstructions: '',
    id: 2,
  },
  {
    photo: "https://www.costafarms.com/CostaFarms/Blue-Fescue-Costa-Farms-Perennial.jpg",
    nickname: "Blue Fescue",
    species: "Festuca glauca",
    h2oFrequency: 'daily',
    careInstructions: '',
    id: 3,
  },
  {
    photo: "https://www.costafarms.com/CostaFarms/Mikania-Purple-Pleasure-Houseplant-Costa-Farms.jpg",
    nickname: "Purple Pleasure Plant",
    species: "Mikania ternata",
    h2oFrequency: 'weekly',
    careInstructions: '',
    id: 4,
  },
  {
    photo: "https://www.costafarms.com/CostaFarms/Pothos-1-Hero-Costa-Farms-Houseplant.jpg",
    nickname: "Pothos",
    species: "Epipremnum aureum",
    h2oFrequency: 'weekly',
    careInstructions: '',
    id: 5,
  },
  {
    photo: "https://www.costafarms.com/CostaFarms/English-Ivy-Costa-Farms-Houseplant-Hero-2.jpg",
    nickname: "Ivy",
    species: "Hedera spp",
    h2oFrequency: 'daily',
    careInstructions: '',
    id: 6,
  },
  {
    photo: "https://www.costafarms.com/CostaFarms/African-Mask-Plant-Costa-Farms-Houseplant.jpg",
    nickname: "Elephant's Ear",
    species: "Alocasia spp",
    h2oFrequency: 'daily',
    careInstructions: '',
    id: 7,
  },
  {
    photo: "https://www.costafarms.com/CostaFarms/Erigeron-Costa-Farms-Perennial-Hero.jpg",
    nickname: "Fleabane",
    species: "Erigeron spp",
    h2oFrequency: 'daily',
    careInstructions: '',
    id: 8,
  },
  {
    photo: "https://www.costafarms.com/CostaFarms/ZZ-Plant-Costa-Farms-Houseplant.jpg",
    nickname: "ZZ Plant",
    species: "Cryptocereus anthonyanus",
    h2oFrequency: 'weekly',
    careInstructions: '',
    id: 9,
  },
  {
    photo: "https://www.costafarms.com/CostaFarms/Costa-Farms-Purple-Waffle-Plant-Houseplant.jpg",
    nickname: "Purple Waffle Plant",
    species: "Zamioculcas zamiifolia",
    h2oFrequency: 'daily',
    careInstructions: '',
    id: 10,
  },
]

export default plants;